INSERT INTO superheroes (id, name) VALUES (1, 'Superman');
INSERT INTO superheroes (id, name) VALUES (2, 'Batman');
INSERT INTO superheroes (id, name) VALUES (3, 'Wonder Woman');
INSERT INTO superheroes (id, name) VALUES (4, 'Spider-Man');
INSERT INTO superheroes (id, name) VALUES (5, 'Iron Man');
INSERT INTO superheroes (id, name) VALUES (6, 'Thor');
INSERT INTO superheroes (id, name) VALUES (7, 'Captain America');
INSERT INTO superheroes (id, name) VALUES (8, 'Hulk');
INSERT INTO superheroes (id, name) VALUES (9, 'Black Widow');
INSERT INTO superheroes (id, name) VALUES (10, 'Doctor Strange');
INSERT INTO superheroes (id, name) VALUES (11, 'Wolverine');
INSERT INTO superheroes (id, name) VALUES (12, 'Storm');
INSERT INTO superheroes (id, name) VALUES (13, 'Gambit');
INSERT INTO superheroes (id, name) VALUES (14, 'Deadpool');
INSERT INTO superheroes (id, name) VALUES (15, 'Green Lantern');
INSERT INTO superheroes (id, name) VALUES (16, 'Flash');
INSERT INTO superheroes (id, name) VALUES (17, 'Aquaman');
INSERT INTO superheroes (id, name) VALUES (18, 'Black Panther');
INSERT INTO superheroes (id, name) VALUES (19, 'Ant-Man');
INSERT INTO superheroes (id, name) VALUES (20, 'Vision');
INSERT INTO superheroes (id, name) VALUES (21, 'Scarlet Witch');
INSERT INTO superheroes (id, name) VALUES (22, 'Hawkeye');
INSERT INTO superheroes (id, name) VALUES (23, 'Daredevil');
INSERT INTO superheroes (id, name) VALUES (24, 'Jessica Jones');
INSERT INTO superheroes (id, name) VALUES (25, 'Luke Cage');
INSERT INTO superheroes (id, name) VALUES (26, 'Iron Fist');
INSERT INTO superheroes (id, name) VALUES (27, 'Punisher');
INSERT INTO superheroes (id, name) VALUES (28, 'Blade');
INSERT INTO superheroes (id, name) VALUES (29, 'Ghost Rider');
INSERT INTO superheroes (id, name) VALUES (30, 'Silver Surfer');
INSERT INTO superheroes (id, name) VALUES (31, 'Namor');
INSERT INTO superheroes (id, name) VALUES (32, 'She-Hulk');
INSERT INTO superheroes (id, name) VALUES (33, 'Moon Knight');
INSERT INTO superheroes (id, name) VALUES (34, 'Nova');
INSERT INTO superheroes (id, name) VALUES (35, 'Blue Beetle');
INSERT INTO superheroes (id, name) VALUES (36, 'Booster Gold');
INSERT INTO superheroes (id, name) VALUES (37, 'Firestorm');
INSERT INTO superheroes (id, name) VALUES (38, 'Martian Manhunter');
INSERT INTO superheroes (id, name) VALUES (39, 'Zatanna');
INSERT INTO superheroes (id, name) VALUES (40, 'Green Arrow');
INSERT INTO superheroes (id, name) VALUES (41, 'Atom');
INSERT INTO superheroes (id, name) VALUES (42, 'Spectre');
INSERT INTO superheroes (id, name) VALUES (43, 'Swamp Thing');
INSERT INTO superheroes (id, name) VALUES (44, 'Sandman');
INSERT INTO superheroes (id, name) VALUES (45, 'Constantine');