INSERT INTO superheroes (name) VALUES ('Superman');
INSERT INTO superheroes (name) VALUES ('Batman');
INSERT INTO superheroes (name) VALUES ('Wonder Woman');
INSERT INTO superheroes (name) VALUES ('Spider-Man');
INSERT INTO superheroes (name) VALUES ('Iron Man');
INSERT INTO superheroes (name) VALUES ('Thor');
INSERT INTO superheroes (name) VALUES ('Captain America');
INSERT INTO superheroes (name) VALUES ('Hulk');
INSERT INTO superheroes (name) VALUES ('Black Widow');
INSERT INTO superheroes (name) VALUES ('Doctor Strange');
INSERT INTO superheroes (name) VALUES ('Wolverine');
INSERT INTO superheroes (name) VALUES ('Storm');
INSERT INTO superheroes (name) VALUES ('Gambit');
INSERT INTO superheroes (name) VALUES ('Deadpool');
INSERT INTO superheroes (name) VALUES ('Green Lantern');
INSERT INTO superheroes (name) VALUES ('Flash');
INSERT INTO superheroes (name) VALUES ('Aquaman');
INSERT INTO superheroes (name) VALUES ('Black Panther');
INSERT INTO superheroes (name) VALUES ('Ant-Man');
INSERT INTO superheroes (name) VALUES ('Vision');
INSERT INTO superheroes (name) VALUES ('Scarlet Witch');
INSERT INTO superheroes (name) VALUES ('Hawkeye');
INSERT INTO superheroes (name) VALUES ('Daredevil');
INSERT INTO superheroes (name) VALUES ('Jessica Jones');
INSERT INTO superheroes (name) VALUES ('Luke Cage');
INSERT INTO superheroes (name) VALUES ('Iron Fist');
INSERT INTO superheroes (name) VALUES ('Punisher');
INSERT INTO superheroes (name) VALUES ('Blade');
INSERT INTO superheroes (name) VALUES ('Ghost Rider');
INSERT INTO superheroes (name) VALUES ('Silver Surfer');
INSERT INTO superheroes (name) VALUES ('Namor');
INSERT INTO superheroes (name) VALUES ('She-Hulk');
INSERT INTO superheroes (name) VALUES ('Moon Knight');
INSERT INTO superheroes (name) VALUES ('Nova');
INSERT INTO superheroes (name) VALUES ('Blue Beetle');
INSERT INTO superheroes (name) VALUES ('Booster Gold');
INSERT INTO superheroes (name) VALUES ('Firestorm');
INSERT INTO superheroes (name) VALUES ('Martian Manhunter');
INSERT INTO superheroes (name) VALUES ('Zatanna');
INSERT INTO superheroes (name) VALUES ('Green Arrow');
INSERT INTO superheroes (name) VALUES ('Atom');
INSERT INTO superheroes (name) VALUES ('Spectre');
INSERT INTO superheroes (name) VALUES ('Swamp Thing');
INSERT INTO superheroes (name) VALUES ('Sandman');
INSERT INTO superheroes (name) VALUES ('Constantine');